from io import BytesIO
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF


def build_resume_text(data):
    skills = [s.strip() for s in data.get("skills", "").split(",") if s.strip()]
    soft_skills = [s.strip() for s in data.get("soft_skills", "").split(",") if s.strip()]
    projects = [p.strip() for p in data.get("projects", "").split("\n") if p.strip()]
    experience = [e.strip() for e in data.get("experience", "").split("\n") if e.strip()]
    certifications = [c.strip() for c in data.get("certifications", "").split("\n") if c.strip()]
    achievements = [a.strip() for a in data.get("achievements", "").split("\n") if a.strip()]
    languages = [l.strip() for l in data.get("languages", "").split(",") if l.strip()]

    summary = data.get("summary", "").strip()
    if not summary:
        top = ", ".join(skills[:5]) if skills else "software development"
        summary = (
            f"Motivated {data.get('role', 'Software')} aspirant skilled in {top}. "
            f"Focused on building practical projects and continuous learning."
        )

    header_contact = " | ".join(
        [x for x in [data.get("email", ""), data.get("phone", ""), data.get("location", ""), data.get("links", "")] if x]
    )

    lines = [
        data.get("name", "").upper(),
        f"{data.get('role', '')}  ·  {header_contact}",
        "",
        "PROFESSIONAL SUMMARY",
        summary,
        "",
        "TECHNICAL SKILLS",
        " • ".join(skills) if skills else "-",
    ]

    if soft_skills:
        lines += ["", "SOFT SKILLS", " • ".join(soft_skills)]

    lines += ["", "PROJECTS"]
    lines += [f"• {p}" for p in projects] if projects else ["• Add projects"]

    lines += ["", "EXPERIENCE"]
    lines += [f"• {e}" for e in experience] if experience else ["• Fresher / Academic projects"]

    if certifications:
        lines += ["", "CERTIFICATIONS"] + [f"• {c}" for c in certifications]

    if achievements:
        lines += ["", "ACHIEVEMENTS"] + [f"• {a}" for a in achievements]

    if languages:
        lines += ["", "LANGUAGES", " • ".join(languages)]

    lines += ["", "EDUCATION", data.get("education", "-")]
    return "\n".join(lines)


def export_docx(data) -> bytes:
    text = build_resume_text(data)
    doc = Document()

    section = doc.sections[0]
    section.top_margin = Inches(0.6)
    section.bottom_margin = Inches(0.6)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    lines = text.split("\n")
    # Name
    p = doc.add_paragraph()
    run = p.add_run(lines[0] if lines else "RESUME")
    run.bold = True
    run.font.size = Pt(18)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Contact line
    if len(lines) > 1:
        p2 = doc.add_paragraph(lines[1])
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for r in p2.runs:
            r.font.size = Pt(10)

    section_titles = {
        "PROFESSIONAL SUMMARY", "TECHNICAL SKILLS", "SOFT SKILLS", "PROJECTS",
        "EXPERIENCE", "CERTIFICATIONS", "ACHIEVEMENTS", "LANGUAGES", "EDUCATION"
    }

    for line in lines[2:]:
        if not line.strip():
            continue
        if line.strip() in section_titles:
            p = doc.add_paragraph()
            run = p.add_run(line.strip())
            run.bold = True
            run.font.size = Pt(12)
        else:
            p = doc.add_paragraph(line)
            for r in p.runs:
                r.font.size = Pt(10)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()


class ResumePDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, "Generated by AI Resume Studio", align="C")


def export_pdf(data) -> bytes:
    text = build_resume_text(data)
    pdf = ResumePDF()
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.add_page()
    pdf.set_margins(16, 14, 16)

    lines = text.split("\n")
    # Name
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 9, lines[0] if lines else "RESUME", align="C")

    if len(lines) > 1:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(70, 70, 70)
        pdf.multi_cell(0, 6, lines[1], align="C")
        pdf.ln(2)

    section_titles = {
        "PROFESSIONAL SUMMARY", "TECHNICAL SKILLS", "SOFT SKILLS", "PROJECTS",
        "EXPERIENCE", "CERTIFICATIONS", "ACHIEVEMENTS", "LANGUAGES", "EDUCATION"
    }

    for line in lines[2:]:
        if not line.strip():
            pdf.ln(1)
            continue
        if line.strip() in section_titles:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(30, 64, 175)
            pdf.multi_cell(0, 7, line.strip())
            pdf.set_draw_color(180, 180, 180)
            pdf.line(16, pdf.get_y(), 194, pdf.get_y())
            pdf.ln(2)
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            # FPDF needs latin-1 safe text; replace unsupported chars
            safe = line.encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 6, safe)

    return bytes(pdf.output())